// <auto-generated />
namespace HiringFair.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class employer : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(employer));
        
        string IMigrationMetadata.Id
        {
            get { return "201904121517423_employer"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
